homepage: "https://github.com/butlergroup/macro_paste"
language: rust
primary_contact: "chris.butler@butlergroup.net"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
main_repo: 'https://github.com/butlergroup/macro_paste.git'
